server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 25102005
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: MessageRT/messages
    encoding: UTF-8
    default-locale: en_US
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: YOUR_FACEBOOK_APP_ID
            clientSecret: YOUR_FACEBOOK_APP_SECRET
            scope:
              - email
              - public_profile
api:
  prefix: /api
jwt:
  expiration: 3306006
  expiration-refresh-token: 3306006
  secretKey: ThisIsASecretKey

logging:
  level:
    org:
      springframework.security: DEBUG

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        #include: "health"
        include: "health, info"

kafka:
  bootstrap:
    servers=your-kafka-broker:9092:


